// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1igFCH9dtjqsZxfmstjHmKBbATgdd_pw',
    appId: '1:89192077781:web:8a0244af223d14ec1d055c',
    messagingSenderId: '89192077781',
    projectId: 'group-task-manager-bf21e',
    authDomain: 'group-task-manager-bf21e.firebaseapp.com',
    storageBucket: 'group-task-manager-bf21e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOhNqlLJcaKJrVv2Qda2yAMopUy7ZD7EQ',
    appId: '1:89192077781:android:1d5c2239622922981d055c',
    messagingSenderId: '89192077781',
    projectId: 'group-task-manager-bf21e',
    storageBucket: 'group-task-manager-bf21e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zIv-jYglWaK4N3EX-p3nredfbtnAnYc',
    appId: '1:89192077781:ios:6411bc92d6f596a81d055c',
    messagingSenderId: '89192077781',
    projectId: 'group-task-manager-bf21e',
    storageBucket: 'group-task-manager-bf21e.appspot.com',
    iosBundleId: 'com.example.groupTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7zIv-jYglWaK4N3EX-p3nredfbtnAnYc',
    appId: '1:89192077781:ios:6411bc92d6f596a81d055c',
    messagingSenderId: '89192077781',
    projectId: 'group-task-manager-bf21e',
    storageBucket: 'group-task-manager-bf21e.appspot.com',
    iosBundleId: 'com.example.groupTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1igFCH9dtjqsZxfmstjHmKBbATgdd_pw',
    appId: '1:89192077781:web:ff79867712eb5e671d055c',
    messagingSenderId: '89192077781',
    projectId: 'group-task-manager-bf21e',
    authDomain: 'group-task-manager-bf21e.firebaseapp.com',
    storageBucket: 'group-task-manager-bf21e.appspot.com',
  );
}
